# Generated by Django 2.1.5 on 2019-01-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190125_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_os',
            name='Created',
        ),
    ]
