from django.db import models


class Member(models.Model):
    user_role = models.CharField(max_length=10)
    user_id = models.CharField(max_length=30, primary_key=True)
    user_name = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    businessnum = models.CharField(max_length=30)
    tbc = models.CharField(max_length=30)
    otpkey = models.CharField(max_length=20)
    user_pw = models.CharField(max_length=100)
    c_date = models.DateTimeField(null=True)

    def __str__(self):
        return self.user_id


class Notice(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=1000 * 5)
    c_date = models.DateTimeField(null=True)

    def __str__(self):
        return self.title


class Process(models.Model):
    contract_id = models.CharField(max_length=20)
    OS_hash = models.CharField(max_length=100)
    SR_hash = models.CharField(max_length=100)
    CI_hash = models.CharField(max_length=100)
    LCR_hash = models.CharField(max_length=100)
    LC_hash = models.CharField(max_length=100)
    BL_hash = models.CharField(max_length=100)
    DO_hash = models.CharField(max_length=100)
    user1 = models.CharField(max_length=30)
    user2 = models.CharField(max_length=30)
    user3 = models.CharField(max_length=30)
    user4 = models.CharField(max_length=30)



class Contract_LCR(models.Model):
    contractname = models.CharField(max_length=50)
    contract_id = models.CharField(max_length=20)
    sha256 = models.CharField(max_length=100)
    filename = models.CharField(max_length=100)
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, null=True)
    share3 = models.CharField(max_length=30)
    Created = models.CharField(max_length=20,null=True)
    a = models.CharField(max_length=20,null=True)
    b = models.CharField(max_length=20,null=True)
    c = models.CharField(max_length=20,null=True)
    d = models.CharField(max_length=20,null=True)
    e = models.CharField(max_length=20,null=True)
    f = models.CharField(max_length=20,null=True)
    g = models.CharField(max_length=20,null=True)
    h = models.CharField(max_length=20,null=True)
    i = models.CharField(max_length=20,null=True)
    j = models.CharField(max_length=20,null=True)
    k = models.CharField(max_length=20,null=True)
    l = models.CharField(max_length=20,null=True)
    m = models.CharField(max_length=20,null=True)
    n = models.CharField(max_length=20,null=True)
    o = models.CharField(max_length=20,null=True)


class Contract_LC(models.Model):
    contractname = models.CharField(max_length=50)
    contract_id = models.CharField(max_length=20)
    sha256 = models.CharField(max_length=100)
    filename = models.CharField(max_length=100)
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, null=True)
    share1 = models.CharField(max_length=30)
    share2 = models.CharField(max_length=30)
    Created = models.CharField(max_length=20,null=True)
    a = models.CharField(max_length=20,null=True)
    b = models.CharField(max_length=20,null=True)
    c = models.CharField(max_length=20,null=True)
    d = models.CharField(max_length=20,null=True)
    e = models.CharField(max_length=20,null=True)
    f = models.CharField(max_length=20,null=True)
    g = models.CharField(max_length=20,null=True)
    h = models.CharField(max_length=20,null=True)
    i = models.CharField(max_length=20,null=True)
    j = models.CharField(max_length=20,null=True)
    k = models.CharField(max_length=20,null=True)
    l = models.CharField(max_length=20,null=True)
    m = models.CharField(max_length=20,null=True)
    n = models.CharField(max_length=20,null=True)
    o = models.CharField(max_length=20,null=True)
    p = models.CharField(max_length=20,null=True)
    q = models.CharField(max_length=20,null=True)
    r = models.CharField(max_length=20,null=True)
    s = models.CharField(max_length=20,null=True)
    t = models.CharField(max_length=20,null=True)
    u = models.CharField(max_length=20,null=True)
    v = models.CharField(max_length=20,null=True)
    w = models.CharField(max_length=20,null=True)
    x = models.CharField(max_length=20,null=True)
    y = models.CharField(max_length=20,null=True)
    z = models.CharField(max_length=20,null=True)
    aa = models.CharField(max_length=20,null=True)
    bb = models.CharField(max_length=20,null=True)
    cc = models.CharField(max_length=20,null=True)
    dd = models.CharField(max_length=20,null=True)
    ee = models.CharField(max_length=20,null=True)
    ff = models.CharField(max_length=20,null=True)
    gg = models.CharField(max_length=20,null=True)


class Contract_SR(models.Model):
    contractname = models.CharField(max_length=50)
    contract_id = models.CharField(max_length=20)
    sha256 = models.CharField(max_length=100)
    filename = models.CharField(max_length=100)
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, null=True)
    share4 = models.CharField(max_length=30)
    Created = models.CharField(max_length=20,null=True)
    a = models.CharField(max_length=20,null=True)
    b = models.CharField(max_length=20,null=True)
    c = models.CharField(max_length=20,null=True)
    d = models.CharField(max_length=20,null=True)
    e = models.CharField(max_length=20,null=True)
    f = models.CharField(max_length=20,null=True)
    g = models.CharField(max_length=20,null=True)
    h = models.CharField(max_length=20,null=True)
    i = models.CharField(max_length=20,null=True)
    j = models.CharField(max_length=20,null=True)
    k = models.CharField(max_length=20,null=True)
    l = models.CharField(max_length=20,null=True)
    m = models.CharField(max_length=20,null=True)
    n = models.CharField(max_length=20,null=True)
    o = models.CharField(max_length=20,null=True)


class Contract_CI(models.Model):
    contractname = models.CharField(max_length=50)
    contract_id = models.CharField(max_length=20)
    sha256 = models.CharField(max_length=100)
    filename = models.CharField(max_length=100)
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, null=True)
    share1 = models.CharField(max_length=30)
    Created = models.CharField(max_length=20,null=True)
    a = models.CharField(max_length=20,null=True)
    b = models.CharField(max_length=20,null=True)
    c = models.CharField(max_length=20,null=True)
    d = models.CharField(max_length=20,null=True)
    e = models.CharField(max_length=20,null=True)
    f = models.CharField(max_length=20,null=True)
    g = models.CharField(max_length=20,null=True)
    h = models.CharField(max_length=20,null=True)
    i = models.CharField(max_length=20,null=True)
    j = models.CharField(max_length=20,null=True)
    k = models.CharField(max_length=20,null=True)
    l = models.CharField(max_length=20,null=True)
    m = models.CharField(max_length=20,null=True)
    n = models.CharField(max_length=20,null=True)
    o = models.CharField(max_length=20,null=True)
    p = models.CharField(max_length=20,null=True)
    q = models.CharField(max_length=20,null=True)
    r = models.CharField(max_length=20,null=True)


class Contract_BL(models.Model):
    contractname = models.CharField(max_length=50)
    contract_id = models.CharField(max_length=20)
    sha256 = models.CharField(max_length=100)
    filename = models.CharField(max_length=100)
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, null=True)
    share1 = models.CharField(max_length=30)
    share2 = models.CharField(max_length=30)
    Created = models.CharField(max_length=20,null=True)
    a = models.CharField(max_length=20,null=True)
    b = models.CharField(max_length=20,null=True)
    c = models.CharField(max_length=20,null=True)
    d = models.CharField(max_length=20,null=True)
    e = models.CharField(max_length=20,null=True)
    f = models.CharField(max_length=20,null=True)
    g = models.CharField(max_length=20,null=True)
    h = models.CharField(max_length=20,null=True)
    i = models.CharField(max_length=20,null=True)
    j = models.CharField(max_length=20,null=True)


class Contract_DO(models.Model):
    contractname = models.CharField(max_length=50)
    contract_id = models.CharField(max_length=20)
    sha256 = models.CharField(max_length=100)
    filename = models.CharField(max_length=100)
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, null=True)
    share1 = models.CharField(max_length=30)
    share3 = models.CharField(max_length=30)
    Created = models.CharField(max_length=20,null=True)
    a = models.CharField(max_length=20,null=True)
    b = models.CharField(max_length=20,null=True)
    c = models.CharField(max_length=20,null=True)
    d = models.CharField(max_length=20,null=True)
    e = models.CharField(max_length=20,null=True)
    f = models.CharField(max_length=20,null=True)
    g = models.CharField(max_length=20,null=True)


class Contract_OS(models.Model):
    contractname = models.CharField(max_length=50)
    contract_id = models.CharField(max_length=20)
    sha256 = models.CharField(max_length=100)
    filename = models.CharField(max_length=100)
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, null=True)
    share1 = models.CharField(max_length=30)
    Created = models.CharField(max_length=20,null=True)
    a = models.CharField(max_length=20,null=True)
    b = models.CharField(max_length=20,null=True)
    c = models.CharField(max_length=20,null=True)
    d = models.CharField(max_length=20,null=True)
    e = models.CharField(max_length=20,null=True)
    f = models.CharField(max_length=20,null=True)
    g = models.CharField(max_length=20,null=True)
    h = models.CharField(max_length=20,null=True)
    i = models.CharField(max_length=20,null=True)
    j = models.CharField(max_length=20,null=True)
    k = models.CharField(max_length=20,null=True)
    l = models.CharField(max_length=20,null=True)
    m = models.CharField(max_length=20,null=True)
    n = models.CharField(max_length=20,null=True)
    o = models.CharField(max_length=20,null=True)
